package com.jain.lib;

public interface Sample {
    String cartData = "{\"metaData\":{\"country\":\"\",\"customerRef\":7,\"orderStatus\":2,\"chainRef\":1,\"venueRef\":1,\"bookedBy\":\"CUSTOMER_WEBSITE\",\"customerName\":\"Ankit Jain\",\"customerComment\":\"No Ice\",\"totalOrderValue\":0,\"tip\":0,\"totalItemsAmount\":0,\"deviceId\":\"\",\"addressRef\":2,\"selectedTableNo\":7,\"orderBookingDate\":\"03-03-2021\",\"orderEtaDate\":\"03-03-2021\",\"serviceType\":\"SITTING\"},\"cartItems\":[{\"itemRef\":100,\"itemType\":\"KITCHEN\",\"count\":2,\"volume\":null,\"itemName\":\"Cheese Burger\",\"prepTime\":\"00:10\",\"originalCost\":10,\"vat\":20,\"addOns\":[{\"menuType\":\"BAR\",\"groupRef\":1,\"groupName\":\"Tonic\",\"modifierRef\":1,\"modifier\":\"Coca Cola\",\"cost\":1,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Sides\",\"modifierRef\":1,\"modifier\":\"Nuggets\",\"cost\":2,\"vat\":10}]},{\"itemRef\":100,\"itemType\":\"KITCHEN\",\"count\":1,\"volume\":null,\"itemName\":\"Cheese Burger\",\"prepTime\":\"00:10\",\"originalCost\":10,\"vat\":20,\"addOns\":[{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Sides\",\"modifierRef\":1,\"modifier\":\"Nuggets\",\"cost\":5,\"vat\":20}]},{\"itemRef\":1,\"itemType\":\"BAR\",\"count\":1,\"volume\":\"Medium-50ML \",\"itemName\":\"Glenfidich\",\"prepTime\":\"00:10\",\"originalCost\":12.5,\"vat\":10,\"addOns\":[]}]}";
    String venueDetails = "{\"venue_ref\":1,\"chain_ref\":1,\"venue\":\"Pizza Plaza\",\"sub_domain\":\"https://devcurry.iorder4u.com\",\"description1\":\"2nd Floor\",\"description2\":\"55 Bonchurch Road\",\"description3\":\"\",\"description4\":\"Brighton\",\"description5\":\"BN2 3PJ\",\"account_number\":\"PNB000121313141\",\"store_code\":\"1234567\",\"first_name\":\"Mark\",\"surname\":\"Logan\",\"email\":\"abc@gmail.com\",\"latitude\":\"50.8328987\",\"longitude\":\"-0.1248178\",\"menu_type\":2,\"table_service\":1,\"delivery_service\":1,\"collection_service\":1,\"kerb_side\":1,\"main_description\":\"The best pizza place\",\"logo_img_url\":\"https://pubpaldiag.blob.core.windows.net/o4ubucket/1/1/kitchen/1614602408940.jpg\",\"prim_img_url\":\"https://pubpaldiag.blob.core.windows.net/o4ubucket/1/1/kitchen/1614602356262.jpg\",\"bg_img_url\":\"https://pubpaldiag.blob.core.windows.net/o4ubucket/1/1/kitchen/1614602356262.jpg\",\"css_img_url\":null,\"table_range\":15,\"is_bar_open\":1,\"is_kitchen_open\":1,\"table_open\":1,\"delivery_open\":1,\"collection_open\":1,\"avg_covers_hour\":\"20\",\"action_date_time\":\"2021/03/04 15:45:13\",\"min_order_value\":10,\"collect_order_capcity\":12,\"collect_interval\":10,\"phone_number\":\"01234567890\",\"kitchen_order_capacity\":20}";

    String orderDetails = "{\"cartItems\":[{\"itemName\":\"Test Kitchen\",\"count\":2,\"prepTime\":\"00:20\",\"vat\":20,\"volume\":\"Pint\",\"kitchenRef\":364,\"itemType\":\"KITCHEN\",\"itemRef\":364,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]},{\"itemName\":\"Falafel & Avocado Burger\",\"volume\":null,\"count\":2,\"prepTime\":\"00:30\",\"vat\":2.4,\"kitchenRef\":334,\"itemType\":\"KITCHEN\",\"itemRef\":334,\"cost\":24,\"originalCost\":12,\"groupRef\":null,\"addOns\":[{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":10,\"modifier\":\"Tomatoes\",\"cost\":2.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":11,\"modifier\":\"Olives\",\"cost\":3.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":12,\"modifier\":\"Onions\",\"cost\":1.5,\"vat\":20}]}],\"metaData\":{\"bookedBy\":\"CUSTOMER_WEBSITE\",\"chainRef\":1,\"venueRef\":3,\"customerRef\":51,\"customerName\":\"Ankit Jain\",\"serviceType\":\"SITTING\",\"address_Ref\":1,\"selectedTable\":\"7\",\"orderBookDate\":\"09/03/2021 13:01\",\"orderEtaDate\":\"09/03/2021 16:20\",\"customerComment\":\"No Ice\",\"country\":\"\",\"tipAmount\":0,\"deviceId\":\"\",\"paymentUniqueId\":\"fe4a30722dcb666f42de7baca943976a\",\"transactionId\":\"89447287-5997-410f-9bbb-f94396402bc1\",\"totalOrderAmount\":24.7,\"totalItemsAmount\":24.12,\"amount\":\"1509\",\"totalVat\":0.58}}";

    String orderDetails2 = "{\"cartItems\":[{\"itemName\":\"Pasta\",\"count\":2,\"prepTime\":\"00:20\",\"vat\":20,\"volume\":\"Pint\",\"kitchenRef\":364,\"itemType\":\"KITCHEN\",\"itemRef\":364,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]},{\"itemName\":\"Pizza\",\"volume\":null,\"count\":2,\"prepTime\":\"00:30\",\"vat\":2.4,\"kitchenRef\":334,\"itemType\":\"KITCHEN\",\"itemRef\":334,\"cost\":24,\"originalCost\":12,\"groupRef\":null,\"addOns\":[{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":10,\"modifier\":\"Tomatoes\",\"cost\":2.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":11,\"modifier\":\"Olives\",\"cost\":3.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":12,\"modifier\":\"Onions\",\"cost\":1.5,\"vat\":20}]},{\"itemName\":\"Burger\",\"count\":2,\"prepTime\":\"00:20\",\"vat\":20,\"volume\":\"Pint\",\"kitchenRef\":123,\"itemType\":\"KITCHEN\",\"itemRef\":123,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]}],\"metaData\":{\"bookedBy\":\"CUSTOMER_WEBSITE\",\"chainRef\":1,\"venueRef\":3,\"customerRef\":51,\"customerName\":\"Ankit Jain\",\"serviceType\":\"SITTING\",\"address_Ref\":1,\"selectedTable\":\"7\",\"orderBookDate\":\"09/03/2021 13:40\",\"orderEtaDate\":\"09/03/2021 14:40\",\"customerComment\":\"No Ice\",\"country\":\"\",\"tipAmount\":0,\"deviceId\":\"\",\"paymentUniqueId\":\"fe4a30722dcb666f42de7baca943976a\",\"transactionId\":\"89447287-5997-410f-9bbb-f94396402bc1\",\"totalOrderAmount\":24.7,\"totalItemsAmount\":24.12,\"amount\":\"1509\",\"totalVat\":0.58}}";

    String orderDetails3 = "{\"cartItems\":[{\"itemName\":\"Pasta\",\"count\":2,\"prepTime\":\"00:20\",\"vat\":20,\"volume\":null,\"kitchenRef\":364,\"itemType\":\"KITCHEN\",\"itemRef\":364,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]},{\"itemName\":\"Beer\",\"count\":2,\"prepTime\":\"\",\"vat\":20,\"volume\":\"Pint\",\"barRef\":123,\"itemType\":\"BAR\",\"itemRef\":123,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]},{\"itemName\":\"Pizza\",\"count\":2,\"prepTime\":\"00:30\",\"vat\":2.4,\"volume\":null,\"kitchenRef\":334,\"itemType\":\"KITCHEN\",\"itemRef\":334,\"cost\":24,\"originalCost\":12,\"groupRef\":null,\"addOns\":[{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":10,\"modifier\":\"Tomatoes\",\"cost\":2.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":11,\"modifier\":\"Olives\",\"cost\":3.5,\"vat\":20},{\"menuType\":\"KITCHEN\",\"groupRef\":3,\"groupName\":\"Salads\",\"modifierRef\":12,\"modifier\":\"Onions\",\"cost\":1.5,\"vat\":20}]},{\"itemName\":\"Burger\",\"count\":2,\"prepTime\":\"00:20\",\"vat\":20,\"volume\":\"\",\"kitchenRef\":123,\"itemType\":\"KITCHEN\",\"itemRef\":123,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]},{\"itemName\":\"WhisKey\",\"count\":2,\"prepTime\":\"00:00\",\"vat\":20,\"volume\":\"Pint\",\"barRef\":123,\"itemType\":\"BAR\",\"itemRef\":123,\"cost\":51.98,\"originalCost\":25.99,\"groupRef\":null,\"addOns\":[]}],\"metaData\":{\"bookedBy\":\"CUSTOMER_WEBSITE\",\"chainRef\":1,\"venueRef\":3,\"customerRef\":51,\"customerName\":\"Ankit Jain\",\"serviceType\":\"SITTING\",\"address_Ref\":1,\"selectedTable\":\"7\",\"orderBookDate\":\"09/03/2021 13:40\",\"orderEtaDate\":\"09/03/2021 14:40\",\"customerComment\":\"No Ice\",\"country\":\"\",\"tipAmount\":0,\"deviceId\":\"\",\"paymentUniqueId\":\"fe4a30722dcb666f42de7baca943976a\",\"transactionId\":\"89447287-5997-410f-9bbb-f94396402bc1\",\"totalOrderAmount\":24.7,\"totalItemsAmount\":24.12,\"amount\":\"1509\",\"totalVat\":0.58}}";


    //    quarter1(Jan – Mar),
//    quarter2(April – June),
//    quarter3(July-September),
//    quarter4(October – December),
    enum DAYS {
        today,
        yesterday,
        last7days,
        currentMonth,
        lastMonth,
        quarterCurrent,
        quarterLast,
        quarter1,
        quarter2,
        quarter3,
        quarter4,
        currentYear,
        lastYear,

    }

}
